pickpocket:
	player-distance: 5
	failure-percentage: 50
	damage-on-failure: 2
	alert-player: true
	max-tries-before-cooldown: 3
	cooldown: 5
npc:
	can-rob-npcs: false
	inventory:
		min-items: 1
		max-items: 3
		min-stack-size: 1
		max-stack-size: 16
		min-durability-percentage: 50
		max-durability-percentage: 100
		possible-items:
			- 331
			- 272
			- 351:3
			- 351:15