pickpocket:
    player-distance: 5
    success-percentage: 0.50
    creative-stealing: false
    damage-on-failure: 2
    alert-player: true
    max-tries-before-cooldown: 3
    cooldown: 5
npc:
    can-rob-npcs: false
    inventory:
        min-items: 1
        max-items: 3
        min-stack-size: 1
        max-stack-size: 16
        min-durability-percentage: 0.50
        max-durability-percentage: 1.00
        possible-items:
            - 331
            - 272
            - 351:3
            - 351:15